### ISSUE TITLE
xmltv file won't load

### ISSUE THREAD

**Issue by eric859** [primaeval/script.tvguide.fullscreen#110]
The file is attached

[PKCustom2.zip](https://github.com/primaeval/script.tvguide.fullscreen/files/1186107/PKCustom2.zip)

**Comment by tuxdata** [comment]
it works fine few days.  I Tried severals xml files and none works error msg is:
![tvfullscreen](https://user-images.githubusercontent.com/37743774/38317193-be347f4e-382c-11e8-90c0-634c4e09b110.png)

**Comment by primaeval** [comment]
You'll have to send me a link to the xmltv files or show me the error message in kodi.log.

**Comment by tuxdata** [comment]
....
15:52:02.536 T:140209802962688  NOTICE: Running database version Addons27
15:52:02.536 T:140209802962688  NOTICE: Running database version ViewModes6
15:52:02.536 T:140209802962688  NOTICE: Running database version Textures13
15:52:02.537 T:140209802962688  NOTICE: Running database version MyMusic70
15:52:02.539 T:140209802962688  NOTICE: Running database version MyVideos109
15:52:02.539 T:140209802962688  NOTICE: Running database version TV32
15:52:02.540 T:140209802962688  NOTICE: Running database version Epg11
15:52:02.541 T:140210675661184  NOTICE: start dvd mediatype detection
15:52:02.561 T:140210675661184  NOTICE:   load skin from: /usr/share/kodi/addons/skin.estuary (version: 2.0.8)
15:52:02.608 T:140210675661184 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
15:52:02.660 T:140210675661184  NOTICE: Register - new keyboard device registered on application->keyboard: Keyboard (0000:0000)
15:52:02.660 T:140210675661184  NOTICE: Register - new mouse device registered on application->mouse: Mouse (0000:0000)
15:52:02.669 T:140210675661184  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
15:52:02.669 T:140210675661184  NOTICE: Loaded playercorefactory configuration
15:52:02.669 T:140210675661184  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
15:52:02.669 T:140210675661184  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
15:52:02.678 T:140210675661184  NOTICE: initialize done
15:52:02.678 T:140210675661184  NOTICE: Running the application...
15:52:02.681 T:140210675661184  NOTICE: starting zeroconf publishing
15:52:02.682 T:140208779544320  NOTICE: ES: Starting UDP Event server on port 9777
15:52:02.682 T:140208779544320  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
15:52:02.891 T:140209777784576  NOTICE: AddOnLog: PVR IPTV Simple Client: Loaded 7715 channels.
15:52:02.891 T:140209777784576  NOTICE: PVR Manager: Starting
15:52:03.778 T:140208752256768  NOTICE: PVR Manager: Started
15:52:03.895 T:140209802962688  NOTICE: Start - EPG thread started
15:52:04.044 T:140209794569984  NOTICE: [plugin.video.youtube] Startup: detected Leia (Kodi-18.0), DASH_SUPPORT_ADDON = True
15:52:04.776 T:140208796329728   ERROR: [plugin.video.iptv.recorder] service started...
15:52:05.057 T:140208536286976   ERROR: AddOnLog: PVR IPTV Simple Client: EPG channels not found.
15:52:07.787 T:140210675661184   ERROR: Window Translator: Can't find window mutebug
15:52:07.866 T:140209433843456   ERROR: EXCEPTION: Non-Existent Control 4323
15:52:07.867 T:140209433843456   ERROR: EXCEPTION: Non-Existent Control 6300
15:52:07.868 T:140209433843456   ERROR: EXCEPTION: Non-Existent Control 10300
15:52:07.868 T:140209433843456   ERROR: EXCEPTION: Non-Existent Control 8300
15:52:07.879 T:140209433843456   ERROR: EXCEPTION: Non-Existent Control 8000
15:52:08.369 T:140208503695104   ERROR: /home/data/.kodi/addons/script.tvguide.fullscreen/source.py:392: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if row['value'] != addon.getSetting(key):
15:52:09.549 T:140208503695104   ERROR: Traceback (most recent call last):
15:52:09.549 T:140208503695104   ERROR:   File "/home/data/.kodi/addons/script.tvguide.fullscreen/source.py", line 522, in _updateChannelAndProgramListCaches
15:52:09.549 T:140208503695104   ERROR:     for item in self.source.getDataFromExternal(date, ch_list, progress_callback):
15:52:09.549 T:140208503695104   ERROR:   File "/home/data/.kodi/addons/script.tvguide.fullscreen/source.py", line 1904, in getDataFromExternal
15:52:09.550 T:140208503695104   ERROR:     for v in chain(self.getDataFromExternal2(self.xmltvFile, date, ch_list, progress_callback)):
15:52:09.550 T:140208503695104   ERROR:   File "/home/data/.kodi/addons/script.tvguide.fullscreen/source.py", line 2097, in parseXMLTV
15:52:09.550 T:140208503695104   ERROR:     logoFile = os.path.join(logoFolder, title + '.png')
15:52:09.550 T:140208503695104   ERROR:   File "/usr/lib/python2.7/posixpath.py", line 71, in join
15:52:09.550 T:140208503695104   ERROR:     path +=  b
15:52:09.550 T:140208503695104   ERROR: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
15:52:13.277 T:140210675661184 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
15:52:24.358 T:140210675661184 WARNING: Previous line repeats 1 times.
15:52:24.358 T:140210675661184  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.iptvsimple_2019670763.pvr
15:52:24.359 T:140207949555456  NOTICE: Creating InputStream
15:52:24.920 T:140207949555456  NOTICE: Creating Demuxer
15:52:25.008 T:140207949555456  NOTICE: Opening stream: 0 source: 256
15:52:25.008 T:140207949555456 WARNING: OpenStream - Unsupported stream 0. Stream disabled.
15:52:25.008 T:140207949555456  NOTICE: Opening stream: 1 source: 256
15:52:25.008 T:140207949555456  NOTICE: Finding audio codec for: 86018
15:52:25.008 T:140207949555456  NOTICE: Creating audio thread
15:52:25.009 T:140208503695104  NOTICE: running thread: CVideoPlayerAudio::Process()
15:52:25.009 T:140207949555456  NOTICE: Opening stream: 0 source: 256
15:52:25.009 T:140207949555456  NOTICE: Creating video codec with codec id: 28
15:52:25.009 T:140207949555456  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
15:52:25.009 T:140207949555456  NOTICE: Creating video thread
15:52:25.009 T:140207865198336  NOTICE: running thread: video_thread
15:52:25.009 T:140207949555456  NOTICE: Opening stream: 1 source: 256
15:52:25.011 T:140207856805632  NOTICE: COutput::OnStartup: Output Thread created
15:52:25.019 T:140208503695104  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
15:52:25.092 T:140210675661184  NOTICE: GL: Selecting YUV 2 RGB shader
15:52:25.097 T:140210675661184  NOTICE: GL: NPOT texture support detected
15:52:25.097 T:140210675661184  NOTICE: GL: Using GL_ARB_pixel_buffer_object
15:52:25.097 T:140210675661184  NOTICE: Using GL_TEXTURE_2D
15:52:25.258 T:140210150143744  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
15:52:25.640 T:140207865198336  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
15:52:33.373 T:140210675661184   ERROR: Control 11 in window 10609 has been asked to focus, but it can't
15:52:35.755 T:140209433843456   ERROR: Previous line repeats 34 times.
15:52:35.755 T:140209433843456   ERROR: 'Unable to set locale to en: unsupported locale setting'
15:52:35.756 T:140209433843456 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
15:52:35.768 T:140209433843456  NOTICE: [xbmcswift2] Request for "/full_service" matches rule for function "full_service"
15:52:36.081 T:140210675661184   ERROR: Control 11 in window 10609 has been asked to focus, but it can't
15:52:37.346 T:140209433843456 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
15:52:58.620 T:140210675661184 WARNING: Previous line repeats 15433 times.
15:52:58.620 T:140210675661184  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.iptvsimple_2006466917.pvr
15:52:58.688 T:140210675661184  NOTICE: GL: Selecting YUV 2 RGB shader
15:52:58.783 T:140210675661184  NOTICE: GL: NPOT texture support detected
15:52:58.783 T:140210675661184  NOTICE: GL: Using GL_ARB_pixel_buffer_object
15:52:58.783 T:140210675661184  NOTICE: Using GL_TEXTURE_2D
15:52:58.991 T:140207949555456  NOTICE: Creating InputStream
15:52:59.246 T:140207949555456  NOTICE: Creating Demuxer
15:52:59.358 T:140207949555456  NOTICE: Opening stream: 0 source: 256
15:52:59.358 T:140207949555456 WARNING: OpenStream - Unsupported stream 0. Stream disabled.
15:52:59.358 T:140207949555456  NOTICE: Closing stream player 2
15:52:59.358 T:140207949555456  NOTICE: waiting for video thread to exit
15:52:59.358 T:140207865198336   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
15:52:59.358 T:140207865198336  NOTICE: thread end: video_thread
15:52:59.359 T:140207949555456  NOTICE: deleting video codec
15:52:59.359 T:140207949555456  NOTICE: VAAPI::Close
15:52:59.359 T:140207856805632  NOTICE: COutput::OnExit: Output Thread terminated
15:52:59.359 T:140207949555456  NOTICE: VAAPI::Close - closing decoder context
15:52:59.359 T:140207949555456  NOTICE: Opening stream: 1 source: 256
15:52:59.359 T:140207949555456  NOTICE: Finding audio codec for: 86018
15:52:59.360 T:140207949555456  NOTICE: Opening stream: 0 source: 256
15:52:59.360 T:140207949555456  NOTICE: Creating video codec with codec id: 28
15:52:59.360 T:140207949555456  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
15:52:59.360 T:140207949555456  NOTICE: Creating video thread
15:52:59.360 T:140207856805632  NOTICE: running thread: video_thread
15:52:59.360 T:140207949555456  NOTICE: Opening stream: 1 source: 256
15:52:59.371 T:140207865198336  NOTICE: COutput::OnStartup: Output Thread created
15:52:59.601 T:140207856805632  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
15:53:03.605 T:140210675661184   ERROR: Control 11 in window 10609 has been asked to focus, but it can't
15:53:12.790 T:140210675661184   ERROR: Previous line repeats 57 times.
15:53:12.790 T:140210675661184  NOTICE: Storing total System Uptime
15:53:12.790 T:140210675661184  NOTICE: Saving settings
15:53:12.794 T:140210675661184  NOTICE: Saving skin settings
15:53:12.795 T:140210675661184  NOTICE: stop all
15:53:12.795 T:140210675661184  NOTICE: stop player
15:53:12.795 T:140210675661184  NOTICE: CVideoPlayer::CloseFile()
15:53:12.795 T:140210675661184  NOTICE: VideoPlayer: waiting for threads to exit
15:53:12.796 T:140207949555456  NOTICE: CVideoPlayer::OnExit()
15:53:12.796 T:140207949555456  NOTICE: Closing stream player 1
15:53:12.796 T:140207949555456  NOTICE: Waiting for audio thread to exit
15:53:12.971 T:140208503695104  NOTICE: thread end: CVideoPlayerAudio::OnExit()
15:53:12.972 T:140207949555456  NOTICE: Closing audio device
15:53:13.035 T:140207949555456  NOTICE: Deleting audio codec
15:53:13.035 T:140207949555456  NOTICE: Closing stream player 2
15:53:13.035 T:140207949555456  NOTICE: waiting for video thread to exit
15:53:13.038 T:140207856805632  NOTICE: thread end: video_thread
15:53:13.039 T:140207949555456  NOTICE: deleting video codec
15:53:13.265 T:140210150143744  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
15:53:13.327 T:140210675661184  NOTICE: VideoPlayer: finished waiting
15:53:13.327 T:140210675661184  NOTICE: VAAPI::Close
15:53:13.327 T:140207865198336  NOTICE: COutput::OnExit: Output Thread terminated
15:53:13.328 T:140210675661184  NOTICE: VAAPI::Close - closing decoder context
15:53:13.329 T:140210675661184  NOTICE: CVideoPlayer::CloseFile()
15:53:13.329 T:140210675661184  NOTICE: VideoPlayer: waiting for threads to exit
15:53:13.329 T:140210675661184  NOTICE: VideoPlayer: finished waiting
15:53:13.335 T:140210675661184  NOTICE: ES: Stopping event server
15:53:13.335 T:140210675661184  NOTICE: stopping zeroconf publishing
15:53:13.752 T:140208779544320  NOTICE: ES: UDP Event server stopped
15:53:13.752 T:140210675661184  NOTICE: stop dvd detect media
15:53:14.399 T:140210675661184  NOTICE: closing down remote control service
15:53:14.400 T:140210675661184  NOTICE: stopped
15:53:14.600 T:140210675661184  NOTICE: destroy


############### END LOG FILE ################

############ END Kodi CRASH LOG #############o

**Comment by primaeval** [comment]
You've got a strange unicode setting in one of these settings in the settings.xml file.
https://github.com/primaeval/script.tvguide.fullscreen/blob/master/source.py#L58
Have a look in addon_data\script.tvguide.fullscreen\settings.xml for anything non-ascii.

It is also complaining about your channel logos. Have you got channel names with unicode characters?

**Comment by tuxdata** [comment]
well I found this:
<setting id="last.channel" default="true">[&quot;Canal+&quot;, &quot;Canal+&quot;, null, &quot;http://www.programme-television.org/logo_channels/35x35/chaine_34.png&quot;, null, 1, 40]</setting> well I am surprise that copy paste show me " here and & quot in the xml file

**Comment by primaeval** [comment]
I don't think it is the + but it might be.
It is failing trying to join the channel logo folder to the channel title.
https://github.com/primaeval/script.tvguide.fullscreen/blob/master/source.py#L2097
Try changing
`logoFile = os.path.join(logoFolder, title + '.png')`
to
`logoFile = os.path.join(logoFolder, title.encode("utf8") + '.png')`
or
`logoFile = os.path.join(logoFolder, title.decode("utf8") + '.png')`
I expect it is encode you need.

Does your logo folder have any non-ascii characters in it?

If it works I'll make a new release.

**Comment by tuxdata** [comment]
Yess "encode(""utf8)" works! Thanks a lot. For info I'm under Gnu/Linux and kodi 18!
![capture du 2018-04-04 20-57-27](https://user-images.githubusercontent.com/37743774/38328384-177d4522-384b-11e8-9258-b1237cec4309.png)

**Comment by primaeval** [comment]
Good I'll add the fix in.

**Comment by primaeval** [comment]
It's in the repo as 0.0.385. Could you check it works ok.

**Comment by tuxdata** [comment]
It works fine: 
![m6](https://user-images.githubusercontent.com/37743774/38331791-807974ac-3854-11e8-9fdd-36411e4190c6.png)

**Comment by primaeval** [comment]
:) Good.
These utf8 encoding errors are a never-ending problem in python.

**Comment by lonnietc** [comment]
Hi All,

I am using Kodi 18.8 (Liea) and just installed the "script.tvguide.fullscreen" but am getting the same error as reported here with the latest installed: script.tvguide.fullscreen-0.0.445.zip

from https://github.com/primaeval/repository.primaeval/tree/master/jarvis/script.tvguide.fullscreen

The pertinent log entries seems to be:

2020-10-12 18:23:00.624 T:139691072142016   ERROR: Window Translator: Can't find window mutebug
2020-10-12 18:23:00.645 T:139689583441664   ERROR: EXCEPTION: Non-Existent Control 7004
2020-10-12 18:23:00.651 T:139689583441664   ERROR: EXCEPTION: Non-Existent Control 7100
2020-10-12 18:23:00.659 T:139689583441664   ERROR: EXCEPTION: Non-Existent Control 4323
2020-10-12 18:23:00.987 T:139689583441664   ERROR: [script.tvguide.fullscreen] Remote file couldn't be copied:

Is there a local file that I can use to load instead from from a URL?

Any help would be greatly appreciated.
Cheers
