### ISSUE TITLE
db exception

### ISSUE THREAD

**Issue by primaeval** [primaeval/script.tvguide.fullscreen#22]
```
21:09:32 T:6820   ERROR: Exception in thread Thread-206:
                                            Traceback (most recent call last):
                                              File "C:\Kodi16.1\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Kodi16.1\system\python\Lib\threading.py", line 1082, in run
                                                self.function(*self.args, **self.kwargs)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 801, in waitForPlayBackStopped
                                                self._updateNextUpInfo()
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 822, in _updateNextUpInfo
                                                self._populateNextUpInfo()
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 850, in _populateNextUpInfo
                                                nextOsdProgram = self.database.getNextProgram(self.currentProgram)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\source.py", line 609, in getNextProgram
                                                return self._invokeAndBlockForResult(self._getNextProgram, channel)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\source.py", line 188, in _invokeAndBlockForResult
                                                del self.eventResults[method.__name__]
                                            KeyError: '_getNextProgram'
21:09:53 T:3408   ERROR: Exception in thread Thread-190:
                                            Traceback (most recent call last):
                                              File "C:\Kodi16.1\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Kodi16.1\system\python\Lib\threading.py", line 1082, in run
                                                self.function(*self.args, **self.kwargs)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 801, in waitForPlayBackStopped
                                                self._updateNextUpInfo()
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 822, in _updateNextUpInfo
                                                self._populateNextUpInfo()
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 850, in _populateNextUpInfo
                                                nextOsdProgram = self.database.getNextProgram(self.currentProgram)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\source.py", line 609, in getNextProgram
                                                return self._invokeAndBlockForResult(self._getNextProgram, channel)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\source.py", line 188, in _invokeAndBlockForResult
                                                del self.eventResults[method.__name__]
                                            KeyError: '_getNextProgram'
```

**Comment by primaeval** [comment]
wrapped it in a try block
