### ISSUE TITLE
missing current channel on play

### ISSUE THREAD

**Issue by primaeval** [primaeval/script.tvguide.fullscreen#39]
There seems to be a lot of initialisation of the current channel that doesn't get set the first time you play channels in various windows.

**Comment by primaeval** [comment]
eg

```
08:52:58 T:8084   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'title'
                                            Traceback (most recent call last):
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 336, in onAction
                                                self.onActionTVMode(action)
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 363, in onActionTVMode
                                                self._showOsd()
                                              File "C:\Kodi16.1\portable_data\addons\script.tvguide.fullscreen\gui.py", line 1142, in _showOsd
                                                self.setControlLabel(self.C_MAIN_OSD_CHANNEL_TITLE, self.osdChannel.title)
                                            AttributeError: 'NoneType' object has no attribute 'title'
                                            -->End of Python script error report<--
```
