### ISSUE TITLE
Crashing a lot with recent updates?

### ISSUE THREAD

**Issue by im85288** [primaeval/script.tvguide.fullscreen#50]
It's become very unstable for me with the recent updates, almost constantly freezing.

The latest I seen in the logs was:

`20:23:43 T:140506759685888   ERROR: Exception in thread Thread-4:
                                            Traceback (most recent call last):
                                              File "/home/cvh/Documents/LE-CvH/build.LibreELEC-Generic.x86_64-7.0.2-dvbdrivers/Python-2.7.11/.install_pkg/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/home/cvh/Documents/LE-CvH/build.LibreELEC-Generic.x86_64-7.0.2-dvbdrivers/Python-2.7.11/.install_pkg/usr/lib/python2.7/threading.py", line 1073, in run
                                              File "/storage/.kodi/addons/script.tvguide.fullscreen/gui.py", line 1167, in waitForPlayBackStopped
                                                self.currentProgram = self.database.getCurrentProgram(self.currentChannel)
                                              File "/storage/.kodi/addons/script.tvguide.fullscreen/source.py", line 689, in getCurrentProgram
                                                return self._invokeAndBlockForResult(self._getCurrentProgram, channel)
                                              File "/storage/.kodi/addons/script.tvguide.fullscreen/source.py", line 187, in _invokeAndBlockForResult
                                                del self.eventResults[method.__name__]
                                            KeyError: '_getCurrentProgram'`

**Comment by primaeval** [comment]
I need more log. It stops on a keyerror and doesn't say what key is.
It could well be the self.currentChannel not initialised correctly error.

Wrap the log in three backticks so it gets formatted properly like it shows in here:
https://guides.github.com/features/mastering-markdown/

**Comment by im85288** [comment]
Let's close this, latest versions are not crashing
